### ISSUE TITLE
Support for Eastern European characters

### ISSUE THREAD

**Issue by k0b0** [itsnauman/Postie#4]
Hello,

Everything works as it should, the problem is Postie does not handle Easter European characters well. I tried using local characters in both template.txt and recipient.txt files, both time Postie prints out errors.

As soon as it finds some unknown character, it generates an error (see below). Could it be Postie's problem or my own? I'm running this on Raspbian (derivative of Debian - for Raspberry Pi).

Errors :

Traceback (most recent call last):
  File "/usr/local/bin/postie", line 9, in <module>
    load_entry_point('py-postie==0.1', 'console_scripts', 'postie')()
  File "/usr/local/lib/python2.7/dist-packages/postie/cli.py", line 60, in main
    p.run()
  File "/usr/local/lib/python2.7/dist-packages/postie/main.py", line 141, in run
    self.send_emails()
  File "/usr/local/lib/python2.7/dist-packages/postie/main.py", line 127, in send_emails
    content=self.construct_msg(row))
  File "/usr/local/lib/python2.7/dist-packages/postie/main.py", line 109, in construct_msg
    return self.render_template(**template_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/postie/main.py", line 91, in render_template
    template = Template(fp.read().strip())
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 906, in __new__
    return env.from_string(source, template_class=cls)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 841, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 540, in compile
    source = self._parse(source, name, filename)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 459, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/local/lib/python2.7/dist-packages/jinja2/parser.py", line 32, in __init__
    self.stream = environment._tokenize(source, name, filename, state)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 490, in _tokenize
    source = self.preprocess(source, name, filename)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 484, in preprocess
    self.iter_extensions(), text_type(source))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 37: ordinal not in range(128)

Best regards,

B. Kosir

**Comment by itsnauman** [comment]
What character are you using?

**Comment by k0b0** [comment]
I'm trying to use ščž ŠČŽ.

**Comment by itsnauman** [comment]
Alright @k0b0 . I am working on it
